# Mosquitto 2.x - configuração DIDÁTICA.
# allow_anonymous true NÃO é adequado para produção
# (em produção: usuários/senhas, TLS e ACLs por tópico).

listener 1883
allow_anonymous true

persistence false
log_dest stdout
